services:
  petclinic-app:
    image: petclinic-app:latest
    container_name: petclinic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # volumes:
    #   - ./target:/app/target  
    restart: unless-stopped